[[section-solution-strategy]]
== Lösungsstrategie


[role="arc42help"]
****
.Inhalt
Kurzer Überblick über Ihre grundlegenden Entscheidungen und Lösungsansätze, die jeder, der mit der Architektur zu tun hat, verstanden haben sollte.

.Motivation
Dieses Kapitel motiviert übergreifend die zentralen Gestaltungskriterien für Ihre Architektur. Beschränken Sie sich hier auf das Wesentliche. Detailentscheidungen können immer noch bei den einzelnen Bausteinen oder im Kapitel 10 festgehalten werden. Das Kapitel soll Ihren Lesern die gewählte Strategie verdeutlichen.

.Form
Fassen Sie auf wenigen Seiten die Beweggründe für zentrale Entwurfsentscheidungen zusammen. Motivieren Sie ausgehend von Aufgabenstellung, Qualitätszielen und Randbedingungen, was Sie entschieden haben und warum Sie so entschieden haben. Verweisen Sie – wo nötig – auf weitere Ausführungen in Folgekapiteln.

.Einstiegshilfe
In diesem Kapitel beschreiben wir Stellen im Code anhand von Klassen oder Methode, an
denen wichtige fachliche Funktionalität implementiert ist und/oder die im weiteren
Lebenszyklus der Anwendung potenziell geändert werden.


[cols="1,1,1,1" options="header"]
.Einstiegshilfe
|===
|Fall
|Konsequenz
|Stelle
|Hinweise

|(Beispiel:) Neue Entität einführen
|Ggf. neue UseCases implementieren
|de.arc42.sample.ManagerCRUDImpl
|ggf Factory Methoden erweitern
|===

****

Das System ist als MicroService entworfen. D.h. es sollte eigenständig läuffähig sein und der Außenwelt REST Services
zur Verfügung stellen.

Durch die Verwendung von Spring Boot sind bzgl. des Deploments verschiedene Einsatz-Szenarien denkbar:

* als Standalone Applikation mit einem Embedded Tomcat: `java -jar xxx.war`
* als WAR in einem bestehenden Tomcat
* als Docker Container - mittels `mvn package docker:build` lässt sich auf einer entsprechenden Umgebung ein Docker Image
erstellen.

=== Resourcen

Folgende Resourcen stehen zur Verfügung

[plantuml,Domain Classes]
....
Asset "*" -- "*" Snapshot
Token -- "1" Asset
....

==== Assets

Die sind die MetaDaten zu den Blobs. Unterstützt weden GET, POST und DELETE - jeweils Singular und Plural nach gängigen
REST Prinzipien.

==== Tokens

Die sind die MetaDaten zu den Blobs. Unterstützt weden GET, POST - jeweils Singular und Plural nach gängigen
REST Prinzipien.

Beim Erzeugen eines Tokens mittels POST muss eine `MediaID` mitgegeben werden. Mit diesem Token kann dann die entsprechende
Datei heruntergeladen werden `http://localhost:9091/token/993824ur923ur9jd29dj923jd`.

==== Snapshots

Dies sind die Snapshots gemäß der Spezifikation.  Unterstützt weden GET, POST und DELETE - jeweils Singular und Plural
nach gängigen REST Prinzipien.


